name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.3.0
  firebase_core: ^2.15.1   # Asegúrate de usar esta versión
  firebase_auth: ^4.9.0  # Usa esta versión para que sea compatible con firebase_core
  cloud_firestore: ^4.9.1
  intl: ^0.20.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/organic_farming.jpg
    - assets/icons/home_icon.png
    - assets/icons/leaf_icon.png
    - assets/icons/notification_icon.png
    - assets/icons/group_icon.png
    - assets/sustainable_farming.jpg
    - assets/organic_farming_2.jpg


  # Agrega aquí la ruta de tus assets, en este caso las imágenes.
