// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdFQB40Hpwm2NimYPscU57Ot6NA0FdxbQ',
    appId: '1:999185178403:web:05afbc03f31b39aedfb696',
    messagingSenderId: '999185178403',
    projectId: 'agrobin-e9a31',
    authDomain: 'agrobin-e9a31.firebaseapp.com',
    storageBucket: 'agrobin-e9a31.firebasestorage.app',
    measurementId: 'G-43J9LC66SW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcIuAy2Cxbra5YlqYZiQUtErMwTvnCYME',
    appId: '1:999185178403:android:47f09ffdab506479dfb696',
    messagingSenderId: '999185178403',
    projectId: 'agrobin-e9a31',
    storageBucket: 'agrobin-e9a31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvuJ3bQIpagl7qtIRwXHih62IsvVoGzl0',
    appId: '1:999185178403:ios:7b3deea04260c867dfb696',
    messagingSenderId: '999185178403',
    projectId: 'agrobin-e9a31',
    storageBucket: 'agrobin-e9a31.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvuJ3bQIpagl7qtIRwXHih62IsvVoGzl0',
    appId: '1:999185178403:ios:7b3deea04260c867dfb696',
    messagingSenderId: '999185178403',
    projectId: 'agrobin-e9a31',
    storageBucket: 'agrobin-e9a31.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdFQB40Hpwm2NimYPscU57Ot6NA0FdxbQ',
    appId: '1:999185178403:web:99b92df16c9b8431dfb696',
    messagingSenderId: '999185178403',
    projectId: 'agrobin-e9a31',
    authDomain: 'agrobin-e9a31.firebaseapp.com',
    storageBucket: 'agrobin-e9a31.firebasestorage.app',
    measurementId: 'G-3BH72QMLNT',
  );
}
